### ISSUE TITLE
Feature: Stop all/Start all spinners

### ISSUE THREAD

**Issue by tonila** [urish/angular-spinner#28]
Hi,

I need to stop all spinners if server responds with error. Currently it is not possible.

I would implement it with oneliner:
angular-spinner.js:

```
scope.$on('us-spinner:stop', function (event, key) {
    if (key === scope.key || key === undefined) {
        scope.stop();
    }
});
```

**Comment by zuzusik** [comment]
+1, we have this case in our code.

**Comment by KrilYura** [comment]
+1

**Comment by marknadig** [comment]
@urish I was just needing this as well. I want our "global" $http response error handler to turn off all spinners. My first thought was something similar to @tonila 's approach, but rather than an empty string, perhaps a "*" would be more clear on the intent. Then I thought a more generic approach my just be to support regex.

    scope.$on('us-spinner:stop', function (event, key) {
        if (scope.key.match(key) {
            scope.stop();
        }
    });

This leads to a lot of flexibility, provides backward compatibility and no special case characters.  I appreciate any feedback. Would love to send a PR in for this if you agree.

**Comment by Attrash-Islam** [comment]
Hey guys,
I liked the two approaches. Let's wait for @marknadig to fix his pull request and then we'll discuss in which way we're going.

Thanks for you all :1st_place_medal:

**Comment by marknadig** [comment]
@Attrash-Islam sorry, off on another non-ng project :/   So, I don't have the bandwidth to fix this PR right now.

**Comment by Attrash-Islam** [comment]
I'll add the simplest approach suggested by this issue reporter, and I'll give the credits in the commit message with more unit tests to cover this case, and adding this feature to the README file
