### ISSUE TITLE
Using angular-spinner with requirejs custom config

### ISSUE THREAD

**Issue by lripo** [urish/angular-spinner#61]
I'm using requirejs to load angular and angular-spinner and I cannot use a custom path configuration. I think that it's because it's required under the name 'spin.js' (using a dot) in the line 116: `define(['angular', 'spin.js'], factory);`
I'm not an expert using requirejs, but it seems that names with dots cannot be aliased. I'm trying to use a config like this:

    require.config({
        appDir: '',
        baseUrl: './js',
        paths: {
            'angular': '../vendor/angular/angular.min',
            'spin.js': '../vendor/spin.js/spin.min'
        }
     });

But it does not work. If I just change line 116 to `define(['angular', 'spin'], factory);`, and then configure my path as ` 'spin': '../vendor/spin.js/spin.min'`, then everything works at expected.

What do you think? Should it be changed?

**Comment by k7sleeper** [comment]
We have the same issue. Until v0.6.x we worked successfully with
```
require.config({
    baseUrl: './app',
    paths: {
        'angular': '../vendor/angular/angular.min',
        'spin': '../vendor/spin.js/spin.min'
    }
 });
```
After updating to v0.7.0 the browser tries to load `/spin.js` instead of `/vendor/spin.js/spin.min.js`. Changing require config to 
```
require.config({
    baseUrl: './app',
    paths: {
        'angular': '../vendor/angular/angular.min',
        'spin.js': '../vendor/spin.js/spin.min'
    }
 });
```
does not change anything.
Changing line 116 to define(['angular', 'spin'], factory) works with the 'old' require config.

I guess if you require something whioch ends with `.js`require ignores any path mappings. That may be a bug or a feature in require, I dont know.

**Comment by lripo** [comment]
I've just sent a pull request #63

**Comment by urish** [comment]
Can you please check if the following version does the trick for you?

https://github.com/urish/angular-spinner/blob/5b662876e815c484bda1b4ee8e96e7d9ecbaafad/angular-spinner.js

Thanks!

**Comment by k7sleeper** [comment]
It works!

Thank you very much!

**Comment by urish** [comment]
Excellent, thanks for the feedback!

**Comment by lripo** [comment]
Yes, it works! Thanks a lot!
