### ISSUE TITLE
I've got some installation issue

### ISSUE THREAD

**Issue by heygema** [urish/angular-spinner#91]
After I have done with bower install -> include scripts -> not yet included in module

this happens in my console

```
angular-spinner.js:15 Uncaught TypeError: Cannot read property 'module' of undefinedfactory @ angular-spinner.js:15(anonymous function) @ angular-spinner.js:136(anonymous function) @ angular-spinner.js:138
main.controller.js:21
```

If I add to the app.module the angularSpinner dependency are simply not defined.

I think the problem is from the angular-spinner.js source.
thank you.

**Comment by Attrash-Islam** [comment]
Hi @heygema ,
Thanks for reporting

We've decided to refactor the whole base code because of the many requests of webpack and amd compatibility issues, and we're using already webpack in master branch (+TypeScript).

When we publish the new release in the next days you won't encounter any installation issues

**Comment by heygema** [comment]
Thanks for your concern, webpack is awesome.

**Comment by Attrash-Islam** [comment]
Absolutely!
