### ISSUE TITLE
problem with webpack

### ISSUE THREAD

**Issue by phra** [urish/angular-spinner#92]
hi,

webpack was failing bundling the code due to spin.js package name.
to resolve i had to declare an alias section in webpack.config.js

``` javascript
config.resolve = {
    alias: {
      'spin': 'spin.js'
    }
  };
```

also tracked here -> https://github.com/fgnass/spin.js/issues/323

**Comment by Attrash-Islam** [comment]
Hi @phra ,
Thanks for reporting

We've decided to refactor the whole base code because of the many requests of webpack and amd compatibility issues, and we're using already webpack in master branch (+TypeScript).

Once we publish our new release in the next days, you won't encounter any issue related to build process
