### ISSUE TITLE
Why typescript

### ISSUE THREAD

**Issue by bearcatFulton** [urish/angular-spinner#97]
Why is typescript being used and how should it be implemented.  there is no angular-spinner.js in this file.

**Comment by Attrash-Islam** [comment]
Hi @bearcatFulton ,

I believe that TypeScript is better for the development process, and it's not related to the usage of the plugin since the TypeScript source code is being transpiled finally to a JavaScript code.

If you're asking from the perspective of developer, I believe that TypeScript is more powerful supplying all the ESNext language support with a Typing solid system, which we see that all the community is attracted to (Angular2+ is built upon TypeScript, React folks is starting to use flowjs static type checker, and even one of the most popular state management libraries for React is built on TypeScript which is called Mobx)

(You can read more on that, and I can reference a few great articles on that)

If you're asking from the perspective of user, there will be no changes at all! when we release the new package in the next days, you'll see just JavaScript codes in the node_modules/angular-spinner to link with them, nothing more

For more details, please review the README.md changes

**Comment by Attrash-Islam** [comment]
Second,
angular-spinner.js is not pushed into the git because it's generated output file.

For more read this: https://medium.com/@kentcdodds/why-i-don-t-commit-generated-files-to-master-a4d76382564

**Comment by Attrash-Islam** [comment]
I'll close the issue, Feel free to reopen if needed :wink:

**Comment by slavede** [comment]
I believe that without pushing generated .js file in this case forces developers which are using this to update their (stable) build systems which will make upgrade from 0.8.1 -> 1.x (and next versions) pain so I'm giving 👍  for pushing generated .js file to this repo.

**Comment by Attrash-Islam** [comment]
Thanks @slavede for participating in this discussion.

What is exactly the pain?
`npm install --save angular-spinner`

and
```js 
<script src="node_modules/angular-spinner/dist/index.js"></script>
```
?

**Comment by slavede** [comment]
But when I initially do bower install I do not get node_modules folder.

**Comment by Attrash-Islam** [comment]
Yes. The publish to bower packages will be done today, it's still linked to the old bower package (0.8.x).

Let me update you with the progress later today :smiley:

**Comment by slavede** [comment]
Ooooh, ok then. I thought it will stay this way for bower too. Thanks for the explanation :)

**Comment by Attrash-Islam** [comment]
@urish , Give me permissions for bower package to publish

**Comment by arturskeeled** [comment]
@urish @Attrash-Islam 

While running 
> bower install --save angular-spinner

this happens:

```
bower                        ENOTFOUND Package angular-spinner not found
```

Since I manage all my dependencies with bower as well, this is not working.
Would it be possible for you to publish it ASAP?

**Comment by Attrash-Islam** [comment]
Absolutely @arturskeeled , I'll take care of that ASAP.
Thanks for reporting!

**Comment by Attrash-Islam** [comment]
Fixed. bower install as you like (v.1.0.1)
